//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarberBossI.Exception {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceErrorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BarberBossI.Exception.ResourceErrorMessage", typeof(ResourceErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data deve ser menor ou igual a data atual..
        /// </summary>
        public static string DataMaiorDataAtual {
            get {
                return ResourceManager.GetString("DataMaiorDataAtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição é obrigatório..
        /// </summary>
        public static string DescricaoObrigatoria {
            get {
                return ResourceManager.GetString("DescricaoObrigatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email já cadastrado.
        /// </summary>
        public static string EmailExistente {
            get {
                return ResourceManager.GetString("EmailExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email informado é inválido..
        /// </summary>
        public static string EmailInvalido {
            get {
                return ResourceManager.GetString("EmailInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email é obrigatório..
        /// </summary>
        public static string EmailVazio {
            get {
                return ResourceManager.GetString("EmailVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro desconhecido..
        /// </summary>
        public static string ErroDesconhecido {
            get {
                return ResourceManager.GetString("ErroDesconhecido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faturamento nao encontrado.
        /// </summary>
        public static string FaturamentoNaoEncontrado {
            get {
                return ResourceManager.GetString("FaturamentoNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login e/ou Senha inválidos.
        /// </summary>
        public static string LoginOuSenhaInvalido {
            get {
                return ResourceManager.GetString("LoginOuSenhaInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome é obrigatório..
        /// </summary>
        public static string NomeVazio {
            get {
                return ResourceManager.GetString("NomeVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha inserida e diferente da atual.
        /// </summary>
        public static string SenhaDiferenteDaAtual {
            get {
                return ResourceManager.GetString("SenhaDiferenteDaAtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sua senha deve ter no mínimo 8 caracteres, contendo pelo menos uma letra maiúscula, uma letra minúscula, um número e um caractere especial (por exemplo, !,?,*,.).
        /// </summary>
        public static string SenhaInvalida {
            get {
                return ResourceManager.GetString("SenhaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de pagamento inválido..
        /// </summary>
        public static string TipoPagamentoInvalido {
            get {
                return ResourceManager.GetString("TipoPagamentoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titulo é obrigatório..
        /// </summary>
        public static string TituloObrigatorio {
            get {
                return ResourceManager.GetString("TituloObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor deve ser maior que zero..
        /// </summary>
        public static string ValorMaiorQueZero {
            get {
                return ResourceManager.GetString("ValorMaiorQueZero", resourceCulture);
            }
        }
    }
}
